### ISSUE TITLE
Slice Helper and block.fn

### ISSUE THREAD

**Issue by gather** [raDiesle/Handlebars.js-helpers-collection#1]
It appears for Handlebars 1.0.rc.1, (and possibly older versions) the Slice helper needs to be updated to call the "fn" function inside of block instead of calling block as a function itself.

```
for(i,j; i<j; i++) {
    ret += block.fn(context[i]);
}
```

Otherwise, this will result in the error:

```
Uncaught TypeError: object is not a function 
```

**Comment by raDiesle** [comment]
Thanks

Probably I should move the project forward
Am 05.03.2013 22:04 schrieb "frequentr" notifications@github.com:
